/**
 * dsh-self-restart — lets the agent restart DSH Desktop itself.
 *
 * Why this needs to exist: the agent's bash tool process is a CHILD of the
 * Desktop main process, so `pkill Desktop` from the agent kills its own
 * process tree — including any watchdog it spawned with nohup/disown
 * (those only survive SIGHUP). The watchdog must call setsid() to escape
 * the session entirely, get reparented to launchd, then kill, relaunch,
 * and health-check. Verified end-to-end 2026-09-02 (3s kill→healthy).
 *
 * Exposes one tool: desktop_restart. The tool call itself never returns
 * (the process dies mid-turn); the watchdog writes a status file the next
 * turn can read to confirm the restart succeeded.
 *
 * NOTE: Node strip-only TS — no parameter properties, no enums.
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileIntentStore, continueAfterRestart } from './resume-intent.ts'

export interface Config {
  /** Absolute path of the .app bundle to relaunch. */
  appPath?: string
  /** URL to poll for health after relaunch. */
  healthUrl?: string
  /** Where the watchdog reports progress. */
  statusFile?: string
}

export const name = 'self-restart'
export const inject = ['tools', 'agents']

const DEFAULTS = {
  appPath: '/Applications/DSH Desktop.app',
  healthUrl: 'http://127.0.0.1:43120/',
  statusFile: '/tmp/dsh-self-restart.status',
}

/** The watchdog script, written to disk at apply time (self-contained:
 *  survives the death of everything that spawned it). */
export function watchdogScript(appPath: string, healthUrl: string, statusFile: string): string {
  return `#!/bin/bash
# dsh-self-restart watchdog — generated by the self-restart plugin.
# Runs in a detached session (setsid), survives Desktop teardown.
MARKER=${JSON.stringify(statusFile)}
echo "$(date -u +%FT%TZ) killing" > "$MARKER"
pkill -f "Contents/MacOS/DSH Desktop" || true
for i in $(seq 1 15); do
  pgrep -f "Contents/MacOS/DSH Desktop" >/dev/null || break
  sleep 1
done
if pgrep -f "Contents/MacOS/DSH Desktop" >/dev/null; then
  echo "$(date -u +%FT%TZ) FAILED: still alive after 15s" >> "$MARKER"
  exit 1
fi
echo "$(date -u +%FT%TZ) relaunching" >> "$MARKER"
open -a ${JSON.stringify(appPath)}
for i in $(seq 1 60); do
  if curl -s -o /dev/null --max-time 2 ${JSON.stringify(healthUrl)}; then
    echo "$(date -u +%FT%TZ) HEALTHY after \${i}s" >> "$MARKER"
    exit 0
  fi
  sleep 1
done
echo "$(date -u +%FT%TZ) FAILED: web not healthy after 60s" >> "$MARKER"
exit 1
`
}

/** The detached launcher: double-fork + setsid so the watchdog is reparented
 *  to launchd and survives the death of the Desktop process tree. */
export function launcherSource(scriptPath: string): string {
  return `import os, sys, subprocess
if os.fork() > 0:
    sys.exit(0)
os.setsid()
if os.fork() > 0:
    sys.exit(0)
os.chdir('/')
devnull = os.open(os.devnull, os.O_RDWR)
os.dup2(devnull, 0); os.dup2(devnull, 1); os.dup2(devnull, 2)
subprocess.call(['/bin/bash', ${JSON.stringify(scriptPath)}])
`
}

interface Paths {
  dir: string
  script: string
  launcher: string
}

export function materialize(dir: string, cfg: Required<Config>): Paths {
  mkdirSync(dir, { recursive: true })
  const script = join(dir, 'watchdog.sh')
  const launcher = join(dir, 'launch.py')
  writeFileSync(script, watchdogScript(cfg.appPath, cfg.healthUrl, cfg.statusFile), { mode: 0o755 })
  writeFileSync(launcher, launcherSource(script), { mode: 0o755 })
  return { dir, script, launcher }
}

export function apply(ctx: any, config?: Config) {
  const logger = ctx.logger('self-restart')
  const cfg: Required<Config> = { ...DEFAULTS, ...(config ?? {}) }
  const stateDir = join(process.env.HOME ?? '.', '.dsh', 'profiles', 'desktop', 'state', 'self-restart')
  const paths = materialize(stateDir, cfg)
  const intent = fileIntentStore(stateDir)

  // Boot continuation: if WE restarted and the watchdog confirmed health,
  // wake the requesting session so the agent resumes its work unpoked.
  // Deferred: agents/persistence services settle after apply().
  setTimeout(() => {
    continueAfterRestart({ agents: ctx.agents, intent, statusFile: cfg.statusFile, logger: (m, ...r) => logger.info(m, ...r) })
      .then((outcome) => logger.info(`boot continuation: ${outcome}`))
      .catch((err) => logger.warn('boot continuation failed:', (err as Error).message))
  }, 4000)

  ctx.tools.register({
    name: 'desktop_restart',
    description:
      'Restart the DSH Desktop application. The current turn will be cut off mid-stream ' +
      '(the agent process dies with Desktop); a detached watchdog relaunches Desktop and ' +
      `writes progress to ${cfg.statusFile}. Call this when a restart is needed (e.g. plugin ` +
      'code changes only load at boot). After the restart, read the status file to confirm.',
    parameters: {},
    output: {
      schema: {
        type: 'object',
        additionalProperties: false,
        required: ['launched'],
        properties: { launched: { type: 'boolean' } },
      },
      render: (_args: unknown, value: any) => [{ type: 'text', text: JSON.stringify(value) }],
    },
    async execute(_args: unknown, exec: any) {
      logger.warn('desktop_restart invoked — launching detached watchdog; this turn will die')
      // Record WHO asked so the next boot can wake this session (exec.agent
      // is set by the agent loop, tools/src/index.ts:317).
      if (exec?.agent?.id) {
        try {
          intent.write({ agentId: String(exec.agent.id), requestedAt: new Date().toISOString() })
        } catch (err) { logger.warn('intent write failed:', (err as Error).message) }
      }
      const { spawn } = await import('node:child_process')
      const child = spawn('python3', [paths.launcher], { detached: true, stdio: 'ignore' })
      child.unref()
      // Give the launcher a moment to fork before we (probably) die.
      await new Promise((r) => setTimeout(r, 500))
      return { launched: true }
    },
  })
  logger.info('self-restart active: desktop_restart tool registered')
}
